/**
 * Rebrickable API endpoints for wrapping
 */
export enum Endpoints {
  'Colors' = '/lego/colors',
  'Elements' = '/lego/elements',
  'Themes' = '/lego/themes',
  'Minifigs' = '/lego/minifigs',
  'MinifigParts' = '/lego/minifigs/:set_num/parts',
  'MinifigSets' = '/lego/minifigs/:set_num/sets',
  'Parts' = '/lego/parts',
  'PartColors' = '/lego/parts/:part_num/colors',
  'PartColorsSets' = '/lego/parts/:part_num/colors/:color_id/sets',
  'PartCategories' = '/lego/part_categories',
  'Sets' = '/lego/sets',
  'SetsAlternates' = '/lego/sets/:set_num/alternates',
  'SetsMinifigs' = '/lego/sets/:set_num/minifigs',
  'SetsParts' = '/lego/sets/:set_num/parts',
  'SetsSets' = '/lego/sets/:set_num/sets',
  'UserBadges' = '/users/badges',
  'UserToken' = '/users/_token',
  'UserAllParts' = '/users/:user_token/allparts',
  'UserBuild' = '/users/:user_token/build',
  'UserLostParts' = '/users/:user_token/lost_parts',
  'UserMinifigs' = '/users/:user_token/minifigs',
  'UserPartLists' = '/users/:user_token/partlists',
  'UserPartListParts' = '/users/:user_token/partlists/:list_id/parts',
  'UserParts' = '/users/:user_token/parts',
  'UserProfile' = '/users/:user_token/profile',
  'UserSetLists' = '/users/:user_token/setlists',
  'UserSetListSets' = '/users/:user_token/setlists/:list_id/sets',
  'UserSets' = '/users/:user_token/sets',
  'UserSetSync' = '/users/:user_token/sets/sync',
}
